# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bc379acddd6ef3de2126079bfc673f5f7dd9904fc0e508d50f1b74dcdc6891baf3c22bdad55b2570fe1b6ea970467908db99c2464bba8ce2797ec49b364a7e8

test:
  secret_key_base: 37fb2005139fd453643ece69d89737bd23fcbf7eb817b8cf9eaab8b3cac0fadec99e5391e4b58aca10d067964ec54822b1d833856c9f40e6521770438e5c245f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
